apiVersion: v1
kind: Service
metadata:
  name: secure-nodejs-service
spec:
  type: NodePort
  selector:
    app: secure-nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32000

