name: test project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get a code 
        uses: actions/checkout@v6
      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: install depandecies
        run: npm ci
      - name: run tests
        run: npm test
